path:
  RAW_IMAGE_DATA_PATH: "./data/raw/"
  PROCESSED_IMAGE_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"
  TRAIN_MODELS: "./artifacts/checkpoints/train_models/"
  BEST_MODEL: "./artifacts/checkpoints/best_model/"
  METRICS_PATH: "./artifacts/metrics/"
  TRAIN_OUTPUT_IMAGES: "./artifacts/outputs/train_images/"
  TEST_OUTPUT_IMAGES: "./artifacts/outputs/test_images/"


dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 128
  batch_size: 1
  split_size: 0.20
  mongoDB: False

database:
  USERNAME: None         # Set Your USERNAME
  PASSWORD: None         # Set Your PASSWORD
  CLUSTER_URL: None      # Set Your Cluster e.g. "cluster0.ym14neq.mongodb.net/?appName=Cluster0"

MLFlow:
  MLFLOW_TRACKING_URL: "https://dagshub.com/atikul-islam-sajib/CCGAN.mlflow"  # Set your own MLFlow Tracking URL
  MLFLOW_TRACKING_USERNAME: "atikul-islam-sajib"                              # Set your own MLFlow Tracking Username
  MLFLOW_TRACKING_PASSWORD: "0c9062f98631dcdb3a9b2d56ebba7ff850a19139"                                       # Set your own MLFlow Tracking Password
  REPO_NAME: "CCGAN"

trainer:
  epochs: 2000                      # Number of training epochs
  lr: 0.001                         # Learning rate
  beta1: 0.5                        # Beta1 hyperparameter for Adam optimizer
  beta2: 0.999                      # Beta2 hyperparameter for Adam optimizer
  momentum: 0.90                    # Momentum for optimizers
  weight_decay: 0.001               # Weight decay for regularization
  step_size: 100                    # Step size for learning rate scheduler
  gamma: 0.85                       # Multiplicative factor for learning rate decay
  threshold: 100                    # Threshold for model saving purposes
  device: "cpu"                     # Device to use for training (e.g., MPS, CPU, GPU)
  adam: True                        # Use Adam optimizer
  SGD: False                        # Use SGD optimizer
  pixelLoss: False                  # Use pixel-wise loss
  l1_regularization: False          # Use L1 regularization
  l2_regularization: False          # Use L2 regularization
  elasticnet_regularization: False  # Use Elastic Net regularization
  lr_scheduler: True                # Enable learning rate scheduler
  verbose: True                     # Enable verbose logging
  mlflow: True                      # Enable MLflow tracking


tester:
  model: "best"                     # Model to use for testing (e.g., best model or "./checkpoints/train_models/netG10.pth")
  dataloader: "valid"               # DataLoader to use for validation/testing e.g "train" or "valid"
  device: "cpu"                     # Device to use for testing (e.g., CPU, GPU)


