path:
  RAW_IMAGE_DATA_PATH: "./data/raw/"
  PROCESSED_IMAGE_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"
  TRAIN_MODELS: "./artifacts/checkpoints/train_models/"
  BEST_MODEL: "./artifacts/checkpoints/best_model/"
  METRICS_PATH: "./artifacts/metrics/"
  TRAIN_OUTPUT_IMAGES: "./artifacts/outputs/train_images/"
  TEST_OUTPUT_IMAGES: "./artifacts/outputs/test_images/"


dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 128
  batch_size: 2
  split_size: 0.20
  mongoDB: False

database:
  USERNAME: None         # Set Your USERNAME
  PASSWORD: None         # Set Your PASSWORD
  CLUSTER_URL: None      # Set Your Cluster e.g. "cluster0.ym14neq.mongodb.net/?appName=Cluster0"

MLFlow:
  MLFLOW_TRACKING_URL: "https://dagshub.com/atikul-islam-sajib/CCGAN.mlflow"  # Set your own MLFlow Tracking URL
  MLFLOW_TRACKING_USERNAME: "atikul-islam-sajib"                              # Set your own MLFlow Tracking Username
  MLFLOW_TRACKING_PASSWORD: "*********"                                       # Set your own MLFlow Tracking Password
  REPO_NAME: "CCGAN"

trainer:
  epochs: 1
  lr: 0.001
  beta1: 0.5
  beta2: 0.999
  momentum: 0.90
  weight_decay: 0.001
  step_size: 20
  gamma: 0.85
  device: "mps"
  adam: True
  SGD: False
  pixelLoss: True
  l1_regularization: False
  l2_regularization: False
  elasticnet_regularization: False
  lr_scheduler: False
  verbose: True
  mlflow: True

