path:
  RAW_IMAGE_DATA_PATH: "./data/raw/"
  PROCESSED_IMAGE_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 128
  batch_size: 8
  split_size: 0.20

database:
  USERNAME: "*****"
  PASSWORD: "*****"
  CULSTER_URL: "cluster0.ym14neq.mongodb.net/?appName=Cluster0"

