path:
  RAW_IMAGE_DATA_PATH: "./data/raw/"
  PROCESSED_IMAGE_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 128
  batch_size: 8
  split_size: 0.20
  mongoDB: False

database:
  USERNAME: None         # Set Your USERNAME
  PASSWORD: None         # Set Your PASSWORD
  CLuSTER_URL: None      # Set Your Cluster e.g. "cluster0.ym14neq.mongodb.net/?appName=Cluster0"

